name: 3 publication on website (geodienste.ch)

on:
  schedule:
  - cron:  '0 4 * * MON'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Copy files to website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          # FTP_DIR is defined relatively to the user's "root" directory: ./<...>/monitoring-geodienste-ch/
          server-dir: ${{ secrets.FTP_DIR }}
          protocol: ftps
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/data/**
            **/renv/**
            **/renv.lock
            **/renv/activate.R
            **/renv/settings.dcf
            **/renv/settings.json
            **/.Rprofile
            **/analyse.*
            **/config.R
            **/preprocess.py
            **/Project.Rproj
            **/README.md
            **/requirements.txt
          dry-run: false
