name: geodienste.ch publication on website

on:
  schedule:
  - cron:  '0 4 * * MON'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Copy files to website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ralphstraumann.ch
          username: ralphstr
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /home/ralphstr/public_html/monitoring-geodienste-ch
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt
          dry-run: true
          
          
